volumes:
  hive-dev:
  target:
  cargo-target:

services:
  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: hive-dev
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: hive-local
    volumes:
      - ./dev-container/postgres_init.sh:/docker-entrypoint-initdb.d/create_database.sh:ro
      - hive-dev:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "127.0.0.1", "-d", "hive-local", "-U", "hive-dev"]
      interval: 5s
      timeout: 3s
      retries: 5
  app:
    build:
      context: .
      dockerfile: dev-container/Dockerfile
      args:
        TEST_MODE_DOCKER: ${TEST_MODE_DOCKER:-false}
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/bash", "/app/dev-container/start_app.sh"]
    volumes:
      - .:/app
      - target:/app/target/
      - cargo-target:/app/.cargo/target/
    ports:
      - 3000:3000
      - 3001:3001
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://hive-dev@postgres:5432/hive-local
      TEST_DATABASE_URL: postgres://hive-dev@postgres:5432/hive-test
      TEST_MODE_DOCKER: ${TEST_MODE_DOCKER:-false}
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--output", "/dev/null", "http://localhost:3000/"]
      interval: 5s
      timeout: 5s
      # Allow 15 minutes for startup, then 10 minutes of failed checks at 5s intervals.
      start_period: 15m
      retries: 120
