[unstable]
codegen-backend = true
[profile.apis-dev]
codegen-backend = "cranelift"
[profile.engine-dev]
codegen-backend = "cranelift"
[profile.db-dev]
codegen-backend = "cranelift"
[build]
rustflags = ["-Z", "threads=1","--cfg=web_sys_unstable_apis"]
