#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE "hive-local" WITH OWNER "$POSTGRES_USER";
	CREATE DATABASE "hive-test" WITH OWNER "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE "hive-local" TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE "hive-test" TO "$POSTGRES_USER";
EOSQL
