name: Deploy branch to Fly
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'     
        required: true
        default: 'master'

jobs:
  deploy:
    name: hivegame.test
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
