name: Playwright Tests
on:
  workflow_run:
    workflows: ["Deploy to Fly"]
    types:
      - completed
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: cd apis/end2end && npm ci
    - name: Install Playwright Browsers
      run: cd apis/end2end && npx playwright install --with-deps
    - name: Run Playwright tests
      run: cd apis/end2end && npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: apis/end2end/playwright-report/
        retention-days: 30
